INSERT INTO STUDENT (NAME, AGE) VALUES ('ИВАНОВА',18);
INSERT INTO STUDENT (NAME, AGE) VALUES ('СОКОЛОВА',19);
INSERT INTO STUDENT (NAME, AGE) VALUES ('ПЕТРОВА',20);
INSERT INTO STUDENT (NAME, AGE) VALUES ('ОРЛОВА',21);
INSERT INTO STUDENT (NAME, AGE) VALUES ('ВОРОБЬЕВА',22);